{
    "name": "NGO Donations",
    "version": "1.0",
    "summary": "Manage donors, donations, and project funds for NGOs",
    "author": "Ebidta / Abdul Wahid",
    "category": "Nonprofit",
    "depends": ["contacts", "stock", "sale_management",'payment', "account", "website_sale","purchase","project","website_payment","payment"],
    "data": [
        "security/ir.model.access.csv",
        "data/donation_email_template.xml",
        "wizard/donation_project_transfer_wizard_view.xml",
        "views/donation_projects_views.xml",
        "views/donations_templates_views.xml",
        "views/ngo_donation_views.xml",
        "views/ngo_menu.xml",
        "views/portal_view_update_views.xml",
        "views/res_partner_views.xml",
        "views/product_page_ext.xml",
        "views/donate_payment_template.xml",
        "views/purchase_order_views.xml",
    ],
    'qweb': ['static/src/xml/donation_payment_views.xml'],
    "installable": True,
    "application": True,
}
