from . import student
from . import attendance
from . import fee
from . import classs
from . import result
from . import school_subject
from . import bank
from . import exam
from . import teacher
from . import timetable
from . import salary
from . import salary_settings