from . import ngo_donation
from . import project_project
from . import res_partner
from . import donation_projects
from . import sale_order
from . import purchase_order
from . import donation_project_transfer
from . import payment_transaction
from . import product_template
