{
    "name": "WhatsApp Odoo",
    "summary": "Send WhatsApp messages from Odoo records",
    "version": "19.0.1.0.0",
    "category": "Communication",
    "author": "Custom",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "sale_management",
        "account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_config_parameter_data.xml",
        "data/ir_sequence_data.xml",
        "views/whatsapp_menu.xml",
        "views/whatsapp_message_views.xml",
        "views/whatsapp_gateway_session_views.xml",
        "views/res_config_settings_views.xml",
        "views/whatsapp_send_wizard_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
    ],
    "application": True,
}
